= Joystick Library for Arduino =

This library allows an Arduino board with USB capabilites to act as a Joystick.

Based on the code for the Mouse library and work from
Helm, drake250 and others from the thread http://forum.freetronics.com/viewtopic.php?f=27&t=734

== License ==

Copyright (c) Arduino LLC. All right reserved.
Copyright (c) Tobias Meyer

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
